name: Go
on: 
  pull_request:
  push:
    branches: 
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    name: Validate/Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: validate
      run: |
        # Check that go mod tidy produces a zero diff; clean up any changes afterwards.
        go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 

    - name: test
      run: go test -cover ./...
