name: Test Action
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:

    - name: clone
      uses: actions/checkout@v1
    
    - name: download
      run: |
        go get github.com/mattn/goveralls
        go get github.com/go-playground/overalls    
            
    - name: test
      run: go test -cover -coverprofile coverage.out ./...

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}  
